const fs=require('fs'),vm=require('vm'),assert=require('assert');const s=fs.readFileSync(new URL('../index.js', 'file://' + __filename),'utf8');
function fn(name,indent=2){const prefix=' '.repeat(indent),start=s.indexOf(prefix+'function '+name+'(');assert(start>=0,name);const tail=s.slice(start);if(name==='paintEntries')return tail.split('\n')[0];const end=tail.indexOf('\n'+prefix+'}');return tail.slice(0,end+indent+2)}
function el(){const props=new Map(),classes=new Set();return{dataset:{},children:[],_text:'',set textContent(v){this._text=v;this.children=[]},get textContent(){return this._text},style:{setProperty:(k,v)=>props.set(k,v),removeProperty:k=>props.delete(k)},classList:{toggle:(k,v)=>v?classes.add(k):classes.delete(k),contains:k=>classes.has(k)},append(n){this.children.push(n);n.parentElement=this},setAttribute(){},addEventListener(k,fn){this[k]=fn},props,classes}}
const root=el(),av=el(),button=el(),items=[{id:'icon1',url:'https://example.test/pear.png'}];let saves=0,rendered='';
const nodes={'.bubble-enabled':{checked:false},'.bubble-opacity':{value:100},'.bubble-blur':{value:0},'.opacity-value':{},'.blur-value':{},'.clear-glass':{},'.reset-glass':{},'.bubble-color':{},'.bubble-color-hex':{},'.bubble-color-auto':{},'.text-color-enabled':{},'.text-glow-enabled':{},'.text-color':{},'.text-color-hex':{},'.text-glow-color':{},'.text-glow-hex':{},'.text-glow-size':{},'.text-glow-value':{},'.text-demo':{style:{}},'.text-reset':{}};
const ctx={isHex:v=>/^#[0-9a-f]{6}$/i.test(v||''),isSequence:()=>false,rootVar:()=>'',root,host:{innerWidth:1080,innerHeight:1500},set:{avatar:{},bg:{},frame:{}},byId:id=>items.find(x=>x.id===id),itemUrl:x=>x?.url||'',cssUrl:x=>'url("'+x+'")',keyOf:()=> 'pear.png',bgSize:()=> '100% auto',doc:{createElement:()=>el(),querySelectorAll:()=>[button]},saveSet:()=>saves++,pane:{querySelector:s=>nodes[s]},render:t=>rendered=t};vm.createContext(ctx);
vm.runInContext(['paintBg','paintGlobalBg','paintBubbles','paintText','paintEntry','paintEntries','mgrButton'].map(n=>fn(n)).join('\n')+'\n'+fn('renderBubbles',4)+'\n'+fn('renderText',4),ctx);
ctx.set.bubbles={enabled:true,opacity:0,blur:0};ctx.paintBubbles();assert(root.classes.has('ll-custom-bubbles'));assert.equal(root.props.get('--ll-bubble-opacity'),'0%');assert.equal(root.props.get('--ll-bubble-blur'),'0px');ctx.set.bubbles={enabled:true,opacity:35,blur:18};ctx.paintBubbles();assert.equal(root.props.get('--ll-bubble-opacity'),'35%');assert.equal(root.props.get('--ll-bubble-blur'),'18px');delete ctx.set.bubbles;ctx.paintBubbles();assert(!root.classes.has('ll-custom-bubbles'));assert(!root.props.has('--ll-bubble-opacity'));
ctx.renderBubbles();nodes['.bubble-opacity'].value=55;nodes['.bubble-opacity'].oninput();assert(ctx.set.bubbles.enabled);assert.equal(ctx.set.bubbles.opacity,55);assert(saves>0);nodes['.clear-glass'].onclick();assert.equal(ctx.set.bubbles.opacity,0);assert.equal(ctx.set.bubbles.blur,0);nodes['.reset-glass'].onclick();assert.equal(ctx.set.bubbles,undefined);assert.equal(rendered,'bubbles');
ctx.renderBubbles();nodes['.bubble-color'].value='#bada55';nodes['.bubble-color'].oninput();assert.equal(ctx.set.bubbles.color,'#bada55');assert.equal(root.props.get('--ll-bubble-color'),'#bada55');nodes['.bubble-opacity'].value=45;nodes['.bubble-opacity'].oninput();assert.equal(ctx.set.bubbles.color,'#bada55');nodes['.bubble-color-auto'].onclick();assert(!root.props.has('--ll-bubble-color'));
ctx.renderText();nodes['.text-color'].value='#224466';nodes['.text-color'].oninput();assert.equal(root.props.get('--ll-text-color'),'#224466');assert(root.classes.has('ll-custom-text-color'));nodes['.text-glow-color'].value='#88ffbb';nodes['.text-glow-color'].oninput();assert(root.classes.has('ll-custom-text-glow'));assert.equal(root.props.get('--ll-text-glow-color'),'#88ffbb');nodes['.text-glow-size'].value=11;nodes['.text-glow-size'].oninput();assert.equal(root.props.get('--ll-text-glow-size'),'11px');nodes['.text-color-enabled'].checked=false;nodes['.text-color-enabled'].onchange();assert(!root.classes.has('ll-custom-text-color'));assert(root.classes.has('ll-custom-text-glow'));nodes['.text-reset'].onclick();assert(!root.classes.has('ll-custom-text-glow'));assert(!root.props.has('--ll-text-glow-color'));
ctx.paintEntry(button);assert.equal(button.textContent,'♡');ctx.set.entry={mode:'text',text:'梨梨的头像',size:18};ctx.paintEntry(button);assert.equal(button.textContent,'梨梨的头像');assert.equal(button.props.get('--ll-entry-size'),'18px');ctx.set.entry={mode:'icon',iconId:'icon1',text:'🍐',size:30};ctx.paintEntry(button);assert.equal(button.children[0].src,items[0].url);assert.equal(button.props.get('--ll-entry-size'),'30px');button.children[0].error();assert.equal(button.textContent,'🍐');ctx.set.entry={mode:'icon',iconId:'missing',text:'入口'};ctx.paintEntry(button);assert.equal(button.textContent,'入口');delete ctx.set.entry;ctx.paintEntry(button);assert.equal(button.textContent,'♡');
ctx.set.bg['pear.png']={id:'icon1',x:10,y:20,z:1};ctx.paintBg(av);assert(av.classes.has('ll-custom-avatar-bg'));delete ctx.set.bg['pear.png'];ctx.paintBg(av);assert(!av.classes.has('ll-custom-avatar-bg'));
ctx.set.globalBg={id:'icon1',x:30,y:40,z:1};ctx.paintGlobalBg();assert(root.classes.has('ll-custom-global-bg'));delete ctx.set.globalBg;ctx.paintGlobalBg();assert(!root.classes.has('ll-custom-global-bg'));
let b,clicked=false;ctx.openManager=()=>clicked=true;const edit={before(btn){b=btn;btn.nextElementSibling=this}},mes={querySelector:q=>q==='.mes_edit'?edit:q==='.ll-avatar-entry'?b:av};ctx.mgrButton(mes,av);assert(b.nextElementSibling===edit);b.click({preventDefault(){},stopPropagation(){}});assert(clicked);ctx.mgrButton(mes,av);assert.equal(b.textContent,'♡');
assert(!/function (buildPiano|mountPlayer|strike|audio)\(/.test(s));assert(s.includes('.ll-mgr [hidden]{display:none!important}'));console.log('PASS: custom glass color and theme reset; forced text color and independent glow/color/strength/reset; opacity and blur controls; live save; one-click full transparency; restore theme defaults; custom text/icon/size and image error fallback; entry position/click; prior backgrounds remain functional.');
